version: '3.8'

services:
  web:
    build:
      context: .
      args:
        MAXMIND_ACCOUNT_ID: ${MAXMIND_ACCOUNT_ID}
        MAXMIND_LICENSE_KEY: ${MAXMIND_LICENSE_KEY}

    volumes:
      - .:/app
    ports:
      - "8000:8000"
